<template>
  <div class="main-content">
    <!-- Navigation Bar -->
    <div class="navbar">
      <h1>Dashboard</h1>
      <el-dropdown>
        <span class="el-dropdown-link">
          ADMIN
          <el-icon class="el-icon--right">
            <arrow-down />
          </el-icon>
        </span>
        <template #dropdown>
          <el-dropdown-menu>
            <el-dropdown-item>个人信息</el-dropdown-item>
            <el-dropdown-item>设置</el-dropdown-item>
            <el-dropdown-item divided>退出登录</el-dropdown-item>
          </el-dropdown-menu>
        </template>
      </el-dropdown>
    </div>
    
    <!-- Filter Area -->
    <el-card class="filter-card" shadow="hover">
      <div class="filter-row">
        <div class="filter-item">
          <span class="filter-label">User:</span>
          <el-select 
            v-model="userFilter" 
            filterable 
            clearable 
            placeholder="Enter user ID or email"
            style="width: 200px"
          >
            <el-option 
              v-for="user in uniqueUsers" 
              :key="user.email" 
              :label="user.email" 
              :value="user.email"
            />
          </el-select>
        </div>
        
        <div class="filter-item">
          <span class="filter-label">Model:</span>
          <el-select 
            v-model="modelFilter" 
            placeholder="All Models" 
            clearable
            style="width: 150px"
          >
            <el-option label="All Models" value=""></el-option>
            <el-option 
              v-for="model in modelOptions" 
              :key="model" 
              :label="model" 
              :value="model"
            />
          </el-select>
        </div>
        
        <div class="filter-item">
          <span class="filter-label">Date Range:</span>
          <el-date-picker
            v-model="dateRange"
            type="daterange"
            range-separator="to"
            start-placeholder="Start date"
            end-placeholder="End date"
            format="YYYY-MM-DD"
            value-format="YYYY-MM-DD"
            style="width: 290px"
          />
        </div>
        
        <div class="filter-item">
          <span class="filter-label">Time:</span>
          <el-select 
            v-model="timeGranularity" 
            placeholder="Select"
            style="width: 120px"
          >
            <el-option label="Hourly" value="hourly"></el-option>
            <el-option label="Daily" value="daily"></el-option>
            <el-option label="Weekly" value="weekly"></el-option>
            <el-option label="Monthly" value="monthly"></el-option>
          </el-select>
        </div>
        
        <div class="filter-buttons">
          <el-button type="primary" @click="handleSearch">
            <el-icon><search /></el-icon>
            Search
          </el-button>
          <el-button @click="handleReset" plain>Reset</el-button>
        </div>
      </div>
    </el-card>
    
    <!-- Key Metrics -->
    <el-row :gutter="20" class="metrics-row">
      <el-col :span="6">
        <el-card class="metric-card" shadow="hover">
          <div class="metric-header">
            <span class="metric-title">Total Requests</span>
            <el-tooltip content="Total number of API calls to LLM services" placement="top">
              <el-icon><question-filled /></el-icon>
            </el-tooltip>
          </div>
          <div class="metric-value">1,234</div>
          <div class="metric-change positive">
            <el-icon><top /></el-icon>
            12%
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="metric-card" shadow="hover">
          <div class="metric-header">
            <span class="metric-title">Input Tokens</span>
            <el-tooltip content="Total tokens sent to models as prompts" placement="top">
              <el-icon><question-filled /></el-icon>
            </el-tooltip>
          </div>
          <div class="metric-value">45.6K</div>
          <div class="metric-change positive">
            <el-icon><top /></el-icon>
            8%
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="metric-card" shadow="hover">
          <div class="metric-header">
            <span class="metric-title">Output Tokens</span>
            <el-tooltip content="Total tokens generated by models as responses" placement="top">
              <el-icon><question-filled /></el-icon>
            </el-tooltip>
          </div>
          <div class="metric-value">78.9K</div>
          <div class="metric-change positive">
            <el-icon><top /></el-icon>
            15%
          </div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card class="metric-card" shadow="hover">
          <div class="metric-header">
            <span class="metric-title">Avg Response</span>
            <el-tooltip content="Average response time in milliseconds" placement="top">
              <el-icon><question-filled /></el-icon>
            </el-tooltip>
          </div>
          <div class="metric-value">235ms</div>
          <div class="metric-change negative">
            <el-icon><bottom /></el-icon>
            5%
          </div>
        </el-card>
      </el-col>
    </el-row>
    
    <!-- Network-wide Model Usage Chart -->
    <el-card class="chart-card" shadow="hover">
      <template #header>
        <div class="card-header">
          <span class="card-title">Network-wide Model Usage</span>
        </div>
      </template>
      <div class="chart-container" ref="networkModelUsageChart"></div>
      <div class="chart-legend">
        <div class="legend-item" v-for="(color, model) in modelColors" :key="model">
          <div class="legend-color" :style="{backgroundColor: color}"></div>
          <div class="legend-label">{{ model }}</div>
        </div>
      </div>
    </el-card>
    
    <!-- Trend Charts Row -->
    <el-row :gutter="20" class="chart-row">
      <el-col :span="12">
        <el-card class="chart-card" shadow="hover">
          <template #header>
            <div class="card-header">
              <span class="card-title">LLM/VLM/Embedding Total Requests</span>
            </div>
          </template>
          <div class="chart-container" ref="totalRequestsChart"></div>
          <div class="chart-legend">
            <div class="legend-item">
              <div class="legend-line llm"></div>
              <div class="legend-label">LLM</div>
            </div>
            <div class="legend-item">
              <div class="legend-line vlm"></div>
              <div class="legend-label">VLM</div>
            </div>
            <div class="legend-item">
              <div class="legend-line embedding"></div>
              <div class="legend-label">Embedding</div>
            </div>
          </div>
        </el-card>
      </el-col>
      
      <el-col :span="12">
        <el-card class="chart-card" shadow="hover">
          <template #header>
            <div class="card-header">
              <span class="card-title">LLM/VLM/Embedding Total Tokens</span>
            </div>
          </template>
          <div class="chart-container" ref="totalTokensChart"></div>
          <div class="chart-legend">
            <div class="legend-item">
              <div class="legend-line llm"></div>
              <div class="legend-label">LLM</div>
            </div>
            <div class="legend-item">
              <div class="legend-line vlm"></div>
              <div class="legend-label">VLM</div>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>
    
    <el-row :gutter="20" class="chart-row">
      <el-col :span="12">
        <el-card class="chart-card" shadow="hover">
          <template #header>
            <div class="card-header">
              <span class="card-title">Image Models Total Requests</span>
            </div>
          </template>
          <div class="chart-container" ref="imageRequestsChart"></div>
          <div class="chart-legend">
            <div class="legend-item">
              <div class="legend-line dalle"></div>
              <div class="legend-label">DALL-E</div>
            </div>
            <div class="legend-item">
              <div class="legend-line sd"></div>
              <div class="legend-label">SD</div>
            </div>
            <div class="legend-item">
              <div class="legend-line midjourney"></div>
              <div class="legend-label">Midjourney</div>
            </div>
          </div>
        </el-card>
      </el-col>
      
      <el-col :span="12">
        <el-card class="chart-card" shadow="hover">
          <template #header>
            <div class="card-header">
              <span class="card-title">Model Distribution</span>
            </div>
          </template>
          <div class="chart-container" ref="modelDistributionChart"></div>
          <div class="pie-legend">
            <div class="legend-item" v-for="(percentage, model) in modelDistribution" :key="model">
              <div class="legend-color" :style="{backgroundColor: getModelColor(model)}"></div>
              <div class="legend-label">{{ model }} {{ percentage }}%</div>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>
    
    <!-- User Usage Ranking -->
    <el-card class="ranking-card" shadow="hover">
      <template #header>
        <div class="card-header">
          <span class="card-title">User Usage Ranking</span>
          <el-button type="primary" link @click="viewMoreUserDetails">View More</el-button>
        </div>
      </template>
      <el-table 
        :data="topUsers" 
        style="width: 100%" 
        stripe 
        :border="true"
        highlight-current-row
      >
        <el-table-column prop="email" label="User" width="180"></el-table-column>
        <el-table-column prop="successRequests" label="Success Requests">
          <template #default="{ row }">
            <span class="success-text">{{ row.successRequests }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="failedRequests" label="Failed Requests">
          <template #default="{ row }">
            <span class="failed-text">{{ row.failedRequests }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="tokens" label="Tokens"></el-table-column>
        <el-table-column prop="avgResponse" label="Avg Response"></el-table-column>
        <el-table-column prop="models" label="Models"></el-table-column>
      </el-table>
    </el-card>
    
    <!-- Detailed Data Table -->
    <el-card class="data-card" shadow="hover">
      <template #header>
        <div class="card-header">
          <span class="card-title">Detailed Data</span>
        </div>
      </template>
      <el-table 
        :data="recentCalls" 
        style="width: 100%" 
        stripe 
        :border="true"
        highlight-current-row
      >
        <el-table-column prop="timestamp" label="Timestamp" width="120"></el-table-column>
        <el-table-column prop="user" label="User ID/Email" width="180"></el-table-column>
        <el-table-column prop="model" label="Model Version" width="120"></el-table-column>
        <el-table-column prop="inputTokens" label="In-T"></el-table-column>
        <el-table-column prop="outputTokens" label="Out-T"></el-table-column>
        <el-table-column prop="response" label="Response"></el-table-column>
      </el-table>
      <div class="pagination-wrapper">
        <el-pagination
          v-model:currentPage="currentPage"
          v-model:pageSize="pageSize"
          :page-sizes="[5, 10, 20, 50]"
          layout="total, sizes, prev, pager, next, jumper"
          :total="247"
          background
          @size-change="handleSizeChange"
          @current-change="handleCurrentChange"
        />
      </div>
    </el-card>
  </div>
</template>

<script>
import { onMounted, ref, reactive, computed } from 'vue';
import { useRouter } from 'vue-router';
import Chart from 'chart.js/auto';

export default {
  name: 'Dashboard',
  setup() {
    const router = useRouter();
    
    // 过滤条件
    const userFilter = ref('');
    const modelFilter = ref('');
    const dateRange = ref([]);
    const timeGranularity = ref('daily');
    const currentPage = ref(1);
    const pageSize = ref(10);
    
    // Chart references
    const networkModelUsageChart = ref(null);
    const totalRequestsChart = ref(null);
    const totalTokensChart = ref(null);
    const imageRequestsChart = ref(null);
    const modelDistributionChart = ref(null);
    
    // Time labels for charts
    const timeLabels = Array.from({ length: 15 }, (_, i) => `1/${i * 2 + 1}`);
    
    // Sample data
    const modelOptions = [
      'Llama-3',
      'Mistral',
      'Claude',
      'GPT-4',
      'DALL-E',
      'Stable Diffusion',
      'Midjourney'
    ];
    
    const modelColors = {
      'Llama-3': '#4C6EF5',
      'Mistral': '#34D399',
      'Claude': '#F59E0B',
      'GPT-4': '#EC4899',
      'Others': '#9CA3AF'
    };
    
    const modelDistribution = {
      'Llama-3': 40,
      'Mistral': 25,
      'Claude': 15,
      'GPT-4': 12,
      'Others': 8
    };
    
    // 获取模型颜色的辅助函数
    const getModelColor = (model) => {
      return modelColors[model] || '#9CA3AF';
    };
    
    const uniqueUsers = [
      { email: 'user1@x.com' },
      { email: 'user2@x.com' },
      { email: 'user3@x.com' },
      { email: 'user4@x.com' },
      { email: 'user5@x.com' }
    ];
    
    const topUsers = [
      { email: 'user1@x.com', successRequests: '534', failedRequests: '10', tokens: '120K', avgResponse: '220ms', models: 'Llama-3, Claude' },
      { email: 'user2@x.com', successRequests: '423', failedRequests: '5', tokens: '98K', avgResponse: '185ms', models: 'Mistral, GPT-4' },
      { email: 'user3@x.com', successRequests: '287', failedRequests: '15', tokens: '76K', avgResponse: '245ms', models: 'Llama-3' },
      { email: 'user4@x.com', successRequests: '198', failedRequests: '8', tokens: '54K', avgResponse: '195ms', models: 'Claude, DALL-E' },
      { email: 'user5@x.com', successRequests: '156', failedRequests: '3', tokens: '42K', avgResponse: '235ms', models: 'GPT-4, Mistral' },
      { email: 'user6@x.com', successRequests: '145', failedRequests: '10', tokens: '39K', avgResponse: '210ms', models: 'Llama-3' },
      { email: 'user7@x.com', successRequests: '132', failedRequests: '5', tokens: '35K', avgResponse: '200ms', models: 'Mistral' },
      { email: 'user8@x.com', successRequests: '110', failedRequests: '10', tokens: '31K', avgResponse: '255ms', models: 'Claude' },
      { email: 'user9@x.com', successRequests: '98', failedRequests: '2', tokens: '28K', avgResponse: '190ms', models: 'GPT-4' },
      { email: 'user10@x.com', successRequests: '85', failedRequests: '5', tokens: '25K', avgResponse: '225ms', models: 'DALL-E' }
    ];
    
    const recentCalls = [
      { timestamp: '2023-01-30', user: 'user1@x.com', model: 'Llama-3', inputTokens: '256', outputTokens: '512', response: '210ms' },
      { timestamp: '2023-01-30', user: 'user3@x.com', model: 'Mistral', inputTokens: '128', outputTokens: '346', response: '185ms' },
      { timestamp: '2023-01-30', user: 'user2@x.com', model: 'Llama-3', inputTokens: '512', outputTokens: '734', response: '245ms' },
      { timestamp: '2023-01-30', user: 'user5@x.com', model: 'Claude', inputTokens: '345', outputTokens: '678', response: '312ms' },
      { timestamp: '2023-01-29', user: 'user4@x.com', model: 'Mistral', inputTokens: '256', outputTokens: '489', response: '205ms' }
    ];
    
    // Methods
    const handleSearch = () => {
      console.log('搜索条件:', {
        user: userFilter.value,
        model: modelFilter.value,
        dateRange: dateRange.value,
        timeGranularity: timeGranularity.value
      });
    };
    
    const handleReset = () => {
      userFilter.value = '';
      modelFilter.value = '';
      dateRange.value = [];
      timeGranularity.value = 'daily';
    };
    
    const handleSizeChange = (size) => {
      pageSize.value = size;
    };
    
    const handleCurrentChange = (page) => {
      currentPage.value = page;
    };
    
    const viewMoreUserDetails = () => {
      router.push('/user-usage-details');
    };
    
    // Initialize charts on component mount
    onMounted(() => {
      // 设置初始日期
      dateRange.value = ['2023-01-01', '2023-01-31'];
      
      // 确保DOM元素已经加载完成
      setTimeout(() => {
        try {
          console.log("开始初始化图表");
          
          // Network-wide Model Usage (Stacked Bar Chart)
          if (networkModelUsageChart.value) {
            console.log("初始化 Network-wide Model Usage 图表");
            const networkModelUsageCtx = networkModelUsageChart.value.getContext('2d');
            new Chart(networkModelUsageCtx, {
              type: 'bar',
              data: {
                labels: timeLabels,
                datasets: [
                  {
                    label: 'Llama-3',
                    data: [45, 52, 49, 60, 55, 58, 62, 65, 59, 63, 68, 64, 70, 67, 72],
                    backgroundColor: modelColors['Llama-3'],
                  },
                  {
                    label: 'Mistral',
                    data: [25, 30, 28, 32, 29, 31, 35, 33, 36, 34, 38, 36, 39, 37, 40],
                    backgroundColor: modelColors['Mistral'],
                  },
                  {
                    label: 'Claude',
                    data: [15, 18, 16, 20, 18, 17, 19, 21, 20, 22, 19, 23, 21, 24, 22],
                    backgroundColor: modelColors['Claude'],
                  },
                  {
                    label: 'GPT-4',
                    data: [10, 12, 11, 13, 12, 14, 15, 14, 16, 15, 17, 16, 18, 17, 19],
                    backgroundColor: modelColors['GPT-4'],
                  },
                  {
                    label: 'Others',
                    data: [5, 6, 5, 7, 6, 8, 7, 9, 8, 10, 9, 11, 10, 12, 11],
                    backgroundColor: modelColors['Others'],
                  }
                ]
              },
              options: {
                plugins: {
                  legend: {
                    display: false
                  },
                  title: {
                    display: false
                  },
                  tooltip: {
                    mode: 'index',
                    intersect: false
                  }
                },
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                  x: {
                    stacked: true,
                    title: {
                      display: true,
                      text: 'Date'
                    }
                  },
                  y: {
                    stacked: true,
                    title: {
                      display: true,
                      text: 'Number of Requests'
                    }
                  }
                }
              }
            });
          } else {
            console.error("Network-wide Model Usage 图表元素不存在");
          }
          
          // LLM/VLM/Embedding Total Requests
          if (totalRequestsChart.value) {
            console.log("初始化 LLM/VLM/Embedding Total Requests 图表");
            const totalRequestsCtx = totalRequestsChart.value.getContext('2d');
            new Chart(totalRequestsCtx, {
              type: 'bar',
              data: {
                labels: timeLabels,
                datasets: [
                  {
                    label: 'LLM',
                    data: [65, 75, 85, 95, 90, 85, 95, 100, 95, 105, 100, 110, 105, 115, 110],
                    backgroundColor: '#4C6EF5',
                  },
                  {
                    label: 'VLM',
                    data: [40, 45, 55, 60, 55, 50, 60, 65, 60, 70, 65, 75, 70, 80, 75],
                    backgroundColor: '#34D399',
                  },
                  {
                    label: 'Embedding',
                    data: [25, 30, 35, 40, 35, 30, 40, 45, 40, 50, 45, 55, 50, 60, 55],
                    backgroundColor: '#F59E0B',
                  }
                ]
              },
              options: {
                plugins: {
                  legend: {
                    display: false
                  },
                  tooltip: {
                    mode: 'index',
                    intersect: false
                  }
                },
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                  x: {
                    title: {
                      display: true,
                      text: 'Date'
                    }
                  },
                  y: {
                    title: {
                      display: true,
                      text: 'Number of Requests'
                    }
                  }
                }
              }
            });
          } else {
            console.error("LLM/VLM/Embedding Total Requests 图表元素不存在");
          }
          
          // LLM/VLM/Embedding Total Tokens
          if (totalTokensChart.value) {
            console.log("初始化 LLM/VLM/Embedding Total Tokens 图表");
            const totalTokensCtx = totalTokensChart.value.getContext('2d');
            new Chart(totalTokensCtx, {
              type: 'bar',
              data: {
                labels: timeLabels,
                datasets: [
                  {
                    label: 'LLM',
                    data: [120, 140, 160, 180, 170, 165, 185, 190, 180, 200, 190, 210, 200, 220, 210],
                    backgroundColor: '#4C6EF5',
                  },
                  {
                    label: 'VLM',
                    data: [80, 95, 110, 125, 115, 105, 120, 130, 120, 135, 125, 140, 130, 145, 135],
                    backgroundColor: '#34D399',
                  }
                ]
              },
              options: {
                plugins: {
                  legend: {
                    display: false
                  },
                  tooltip: {
                    mode: 'index',
                    intersect: false
                  }
                },
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                  x: {
                    title: {
                      display: true,
                      text: 'Date'
                    }
                  },
                  y: {
                    title: {
                      display: true,
                      text: 'Number of Tokens (K)'
                    }
                  }
                }
              }
            });
          } else {
            console.error("LLM/VLM/Embedding Total Tokens 图表元素不存在");
          }
          
          // Image Models Total Requests
          if (imageRequestsChart.value) {
            console.log("初始化 Image Models Total Requests 图表");
            const imageRequestsCtx = imageRequestsChart.value.getContext('2d');
            new Chart(imageRequestsCtx, {
              type: 'bar',
              data: {
                labels: timeLabels,
                datasets: [
                  {
                    label: 'DALL-E',
                    data: [30, 35, 40, 45, 40, 35, 45, 50, 45, 55, 50, 60, 55, 65, 60],
                    backgroundColor: '#EC4899',
                  },
                  {
                    label: 'SD',
                    data: [25, 28, 32, 35, 32, 29, 33, 36, 33, 39, 36, 42, 39, 45, 42],
                    backgroundColor: '#8B5CF6',
                  },
                  {
                    label: 'Midjourney',
                    data: [15, 17, 20, 22, 20, 18, 21, 23, 21, 25, 22, 27, 24, 29, 26],
                    backgroundColor: '#10B981',
                  }
                ]
              },
              options: {
                plugins: {
                  legend: {
                    display: false
                  },
                  tooltip: {
                    mode: 'index',
                    intersect: false
                  }
                },
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                  x: {
                    stacked: true,
                    title: {
                      display: true,
                      text: 'Date'
                    }
                  },
                  y: {
                    stacked: true,
                    title: {
                      display: true,
                      text: 'Number of Requests'
                    }
                  }
                }
              }
            });
          } else {
            console.error("Image Models Total Requests 图表元素不存在");
          }
          
          // Model Distribution
          if (modelDistributionChart.value) {
            console.log("初始化 Model Distribution 图表");
            const modelDistributionCtx = modelDistributionChart.value.getContext('2d');
            new Chart(modelDistributionCtx, {
              type: 'doughnut',
              data: {
                labels: Object.keys(modelDistribution),
                datasets: [
                  {
                    data: Object.values(modelDistribution),
                    backgroundColor: [
                      modelColors['Llama-3'],
                      modelColors['Mistral'],
                      modelColors['Claude'],
                      modelColors['GPT-4'],
                      modelColors['Others']
                    ],
                    borderWidth: 1
                  }
                ]
              },
              options: {
                plugins: {
                  legend: {
                    display: false
                  },
                  tooltip: {
                    callbacks: {
                      label: function(context) {
                        return `${context.label}: ${context.raw}%`;
                      }
                    }
                  }
                },
                responsive: true,
                maintainAspectRatio: false,
                cutout: '60%'
              }
            });
          } else {
            console.error("Model Distribution 图表元素不存在");
          }
          
        } catch (e) {
          console.error("图表初始化出错:", e);
        }
      }, 500);
    });
    
    return {
      userFilter,
      modelFilter,
      dateRange,
      timeGranularity,
      uniqueUsers,
      modelOptions,
      modelColors,
      modelDistribution,
      getModelColor,
      topUsers,
      recentCalls,
      networkModelUsageChart,
      totalRequestsChart,
      totalTokensChart,
      imageRequestsChart,
      modelDistributionChart,
      currentPage,
      pageSize,
      handleSearch,
      handleReset,
      handleSizeChange,
      handleCurrentChange,
      viewMoreUserDetails
    };
  }
};
</script>

<style scoped>
.main-content {
  padding: 20px;
  background-color: #f5f7fa;
}

.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  height: 70px;
  border-bottom: 1px solid #ebeef5;
  padding: 0 0 20px 0;
}

.navbar h1 {
  font-size: 24px;
  font-weight: 600;
  color: #303133;
}

.el-dropdown-link {
  cursor: pointer;
  font-weight: 500;
  display: flex;
  align-items: center;
}

.filter-card {
  margin-bottom: 20px;
  border-radius: 8px;
  padding: 8px 0;
}

.filter-row {
  display: flex;
  align-items: center;
  flex-wrap: nowrap;
  gap: 20px;
}

.filter-item {
  display: flex;
  align-items: center;
  white-space: nowrap;
  gap: 8px;
}

.filter-label {
  font-size: 14px;
  color: #606266;
  font-weight: 500;
}

.filter-buttons {
  margin-left: auto;
  display: flex;
  gap: 10px;
}

.button-group {
  margin-left: auto;
}

.metrics-row {
  margin-bottom: 20px;
}

.metric-card {
  height: 140px;
  border-radius: 8px;
  transition: all 0.3s;
}

.metric-card:hover {
  transform: translateY(-5px);
}

.metric-header {
  display: flex;
  align-items: center;
  margin-bottom: 12px;
}

.metric-title {
  font-size: 16px;
  font-weight: 500;
  margin-right: 5px;
  color: #606266;
}

.metric-value {
  font-size: 28px;
  font-weight: 600;
  margin: 10px 0;
  color: #303133;
}

.metric-change {
  font-size: 14px;
  display: flex;
  align-items: center;
  gap: 5px;
}

.positive {
  color: #34D399;
}

.negative {
  color: #F56C6C;
}

.chart-card {
  margin-bottom: 20px;
  border-radius: 8px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-title {
  font-size: 16px;
  font-weight: 600;
  color: #303133;
}

.chart-container {
  height: 300px;
  margin-bottom: 10px;
  padding: 10px;
}

.chart-legend {
  display: flex;
  justify-content: center;
  gap: 15px;
  margin-top: 15px;
  flex-wrap: wrap;
}

.legend-item {
  display: flex;
  align-items: center;
  margin-right: 15px;
  margin-bottom: 5px;
}

.legend-color, .legend-line {
  width: 15px;
  height: 15px;
  margin-right: 8px;
  border-radius: 3px;
}

.legend-line {
  height: 4px;
}

.legend-label {
  font-size: 14px;
  color: #606266;
}

.legend-line.llm {
  background-color: #4C6EF5;
}

.legend-line.vlm {
  background-color: #10B981;
}

.legend-line.embedding {
  background-color: #F59E0B;
}

.legend-line.dalle {
  background-color: #EC4899;
}

.legend-line.sd {
  background-color: #8B5CF6;
}

.legend-line.midjourney {
  background-color: #3B82F6;
}

.pie-legend {
  display: flex;
  justify-content: center;
  gap: 15px;
  margin-top: 15px;
  flex-wrap: wrap;
}

.ranking-card, .data-card {
  border-radius: 8px;
  margin-bottom: 20px;
}

.pagination-wrapper {
  margin-top: 20px;
  display: flex;
  justify-content: center;
}

:deep(.el-table th) {
  background-color: #f5f7fa;
  font-weight: 600;
  color: #606266;
}

:deep(.el-pagination.is-background .el-pager li:not(.is-disabled).is-active) {
  background-color: #409EFF;
}

:deep(.el-card__body) {
  padding: 15px 20px;
}

.success-text {
  color: #67C23A;
  font-weight: 500;
}

.failed-text {
  color: #F56C6C;
  font-weight: 500;
}
</style> 